import type { ContinentId, StoryBeat } from "./types";

export const BEATS: Record<string, StoryBeat> = {
  wake: {
    id: "wake",
    act: "0",
    place: "City of Echoes",
    who: "Fracture Hour",
    bg: "/art/elysara-echoes.jpg",
    portrait: "/art/azrael.png",
    text: "Cold stone. A shard on a cord. A diamond burning in the left palm — the Resonance Well was not a gift. The sky over Eden is a cracked white lattice. The System waits for a history before it will write a class.",
    alt: "Cold stone. A shard on a cord. The Well already knows this stone. Somewhere in the lattice a later name waits: Ryx. Submit a history. Again.",
    choices: [
      { id: "path-lapis", tag: "Lapis", label: "Deceived trader. You bought a shard that was already listening.", remember: "azrael" },
      { id: "path-forged", tag: "Forged", label: "Wandering academic. You trained until the mortal limit cracked." },
      {
        id: "path-crucible",
        tag: "Crucible",
        label: "Grief that still has a name. Something in the hour ignited.",
        auto: true,
      },
    ],
  },
  classed: {
    id: "classed",
    act: "0",
    place: "Resonance Well",
    who: "SYSTEM",
    sys: true,
    bg: "/art/azrael.jpg",
    portrait: "/art/azrael.png",
    text: "Class written. Resonance Well marked on the wrist. Overflow possible. Sanity is a resource. Walk the spire. Sit with the hunched man on the guild steps — or file the prompt.",
    choices: [
      {
        id: "to-heartgrim",
        tag: "Walk",
        label: "The hunched immortal is already looking at the shard.",
        auto: true,
        next: "heartgrim",
        person: "heartgrim",
      },
    ],
  },
  heartgrim: {
    id: "heartgrim",
    act: "I",
    place: "Guild Steps",
    who: "Lord Heartgrim",
    bg: "/art/heartgrim.jpg",
    portrait: "/art/heartgrim.png",
    text: "Harmony was an oath. The System is a lock. That shard is a Dual Flow core I forged with Durak. You inherit the duty. Not the love. She had a name. Sssilvara.",
    alt: "You sit before he asks. He notices. The broken circle in his palm is warmer this hour.",
    choices: [
      {
        id: "heartgrim-sit",
        tag: "Oath",
        label: "Sit with him. Let him name the shard.",
        auto: true,
        oath: 18,
        remember: "namedTheShard",
        next: "after-heartgrim",
        person: "sssilvara",
      },
      {
        id: "heartgrim-form",
        tag: "Control",
        label: "Walk past. File the System form.",
        ctrl: 18,
        next: "after-heartgrim",
      },
    ],
  },
  "after-heartgrim": {
    id: "after-heartgrim",
    act: "I",
    place: "City of Echoes",
    who: "Lord Heartgrim",
    bg: "/art/elysara.jpg",
    portrait: "/art/heartgrim.png",
    text: "The Azure Fields still keep a regulation. Centaurs watch from the ridge and do not come down. Birdmen hold Cloudreach. The first pact is a table, or a form. You already chose.",
    alt: "He does not repeat the name. He does not have to. The Fields still keep their regulation.",
    choices: [
      {
        id: "to-fields",
        tag: "Fields",
        label: "Step into the grass.",
        auto: true,
        next: "fields",
      },
    ],
  },
  fields: {
    id: "fields",
    act: "I",
    place: "Endless Azure Fields",
    who: "Azure Fields",
    bg: "/art/elysara-fields.jpg",
    portrait: "/art/wind-serpent.png",
    text: "Centaurs on the ridge. A wind-serpent writes itself across the cracked sky. Not evil. A regulation. Kima is body. Anima is soul. Dual Pulse is what the System most hates. Open the wells.",
    choices: [
      {
        id: "fight-serpent",
        tag: "Fight",
        label: "Open the wells.",
        auto: true,
        combat: "serpent",
      },
    ],
  },
  "after-serpent": {
    id: "after-serpent",
    act: "I",
    place: "Endless Azure Fields",
    who: "Empress Aeyra Valonyr",
    bg: "/art/aeyra.jpg",
    portrait: "/art/aeyra.jpg",
    text: "Departure licensed pending Empress review. Class confirmed. Emotion flagged as noise — she says it like weather. Seven inhabited continents. The hour will wait. So will the doors.",
    choices: [
      {
        id: "open-map",
        tag: "Eden",
        label: "Open the world.",
        auto: true,
        map: true,
        person: "aeyra",
        remember: "metAeyra",
        oath: 4,
      },
    ],
  },
  xihuang: {
    id: "xihuang",
    act: "II",
    place: "Isychros Capital",
    who: "Sssilvara Coil-Whisperer",
    bg: "/art/xihuang-jadevein.jpg",
    portrait: "/art/sssilvara.jpg",
    text: "Jadevein still holds her vision. A coil in the pool. She is Heartgrim’s slain beloved — not a second romance. Kaisetsu rebuilt this city after the Forge Wars. He will not take a second blow.",
    alt: "The pool remembers you. She does not become yours. The duty still is not love.",
    choices: [
      {
        id: "xihuang-honor",
        tag: "Oath",
        label: "Keep the vision as succession. Take Kaisetsu’s trial.",
        auto: true,
        oath: 12,
        combat: "palm",
        person: "kaisetsu",
      },
      {
        id: "xihuang-use",
        tag: "Control",
        label: "Use the coil as a tool. File the dojo form.",
        ctrl: 12,
        combat: "palm",
        person: "kaisetsu",
      },
    ],
  },
  "xihuang-after": {
    id: "xihuang-after",
    act: "II",
    place: "Isychros Capital",
    who: "Kaisetsu of the Thousand Palms",
    bg: "/art/xihuang-isychros.jpg",
    portrait: "/art/kaisetsu.jpg",
    text: "Fighting is the palm conquering existence’s flow. Tea after. The pact sheds like a scale if you try to wear it. Return to the world when the hour thins.",
    choices: [{ id: "map-x", tag: "Map", label: "Return to Eden.", auto: true, map: true }],
  },
  nordheim: {
    id: "nordheim",
    act: "III",
    place: "Ironhold",
    who: "Durak Ironvein",
    bg: "/art/nordheim-ironhold.jpg",
    portrait: "/art/durak.jpg",
    text: "He measured twice and the world still broke. The amulet’s core was forged here. A sentinel wakes when a Seeker carries a shard it remembers. Name the construct, or it names you.",
    choices: [
      {
        id: "nordheim-name",
        tag: "Oath",
        label: "Name it. Forge a blade that remembers the first amulet.",
        auto: true,
        oath: 12,
        combat: "golem",
        person: "durak",
      },
      {
        id: "nordheim-cap",
        tag: "Control",
        label: "Cap the relic. Let the System hold the name.",
        ctrl: 12,
        combat: "golem",
        person: "durak",
      },
    ],
  },
  "nordheim-after": {
    id: "nordheim-after",
    act: "III",
    place: "Ironhold",
    who: "Durak Ironvein",
    bg: "/art/nordheim.jpg",
    portrait: "/art/durak.jpg",
    text: "Fighting is forging existence from ache. Take the quench. Clan honor is material. Relics can rebel. So can you.",
    choices: [{ id: "map-n", tag: "Map", label: "Return to Eden.", auto: true, map: true }],
  },
  tezcal: {
    id: "tezcal",
    act: "IV",
    place: "Krystallis",
    who: "Xal’thok",
    bg: "/art/tezcal-krystallis.jpg",
    portrait: "/art/xalthok.jpg",
    text: "Living artifacts outlast loyalty. The smile learns a second mouth here: Vexaroth as craft-echo, Zorathax as theology. He was invited. That is why it worked.",
    alt: "He already knows which door you will pick. He smiles like a receipt.",
    choices: [
      {
        id: "tezcal-refuse",
        tag: "Oath",
        label: "Refuse the bargain. Draw on the honest anvil.",
        auto: true,
        oath: 14,
        combat: "smile",
        person: "xalthok",
      },
      {
        id: "tezcal-sign",
        tag: "Control",
        label: "Sign the receipt. Power with a name on it.",
        ctrl: 14,
        combat: "smile",
        person: "xalthok",
      },
    ],
  },
  "tezcal-after": {
    id: "tezcal-after",
    act: "IV",
    place: "Embercrag",
    who: "Xal’thok",
    bg: "/art/tezcal-embercrag.jpg",
    portrait: "/art/xalthok.jpg",
    text: "Existing is the fall from the top to the bottom’s truth. He is not done. The hour is not a duel you finish. It is a smile you carry.",
    choices: [{ id: "map-t", tag: "Map", label: "Return to Eden.", auto: true, map: true }],
  },
  abyssara: {
    id: "abyssara",
    act: "V",
    place: "Depthcall",
    who: "Abyssara",
    bg: "/art/abyssara-depthcall.jpg",
    portrait: "/art/abyssara.jpg",
    text: "The sea as a second sky. Aquavelle’s change nurtures and drowns. A moon-portal opens that is not a moon. False eternal-moon rites are Betrayer work using a borrowed name.",
    choices: [
      {
        id: "abyssara-mend",
        tag: "Oath",
        label: "Mend the tide. Do not flood a rival coast.",
        auto: true,
        oath: 12,
        combat: "tide",
      },
      {
        id: "abyssara-flood",
        tag: "Control",
        label: "Use the portal as written. File the drowning.",
        ctrl: 12,
        combat: "tide",
      },
    ],
  },
  "abyssara-after": {
    id: "abyssara-after",
    act: "V",
    place: "Silk Dunes",
    who: "Abyssara",
    bg: "/art/abyssara-dunes.jpg",
    text: "Tenebris is not a nineteenth god. The dune does not keep a throne. It keeps a fire. The hour thins toward the bottom of the world.",
    choices: [{ id: "map-a", tag: "Map", label: "Return to Eden.", auto: true, map: true }],
  },
  vindraeth: {
    id: "vindraeth",
    act: "VI",
    place: "Blighted Wilds",
    who: "Thorne Voidwarden",
    bg: "/art/vindraeth-wilds.jpg",
    portrait: "/art/thorne.jpg",
    text: "No city. Beauty that should not bloom. Thorne’s profession is grief. The Fracture was not weather. It was a murder, and the world became a warden rather than trust again.",
    choices: [
      {
        id: "vindraeth-seal",
        tag: "Oath",
        label: "Take the seal. Isolation is the cost.",
        auto: true,
        oath: 16,
        remember: "sealedTheBottom",
        next: "vindraeth-after",
        person: "thorne",
      },
      {
        id: "vindraeth-undeath",
        tag: "Control",
        label: "Accept the offer of eternal life. It is undeath.",
        ctrl: 16,
        next: "vindraeth-after",
        person: "thorne",
      },
    ],
  },
  "vindraeth-after": {
    id: "vindraeth-after",
    act: "VI",
    place: "Shattered Spires",
    who: "Thorne Voidwarden",
    bg: "/art/vindraeth-spires.jpg",
    portrait: "/art/thorne.jpg",
    text: "Fighting is the seal on existence’s tears. Crawl correctly. The next Seeker will have to survive this too. His name is already in the lattice.",
    choices: [{ id: "map-v", tag: "Map", label: "Return to Eden.", auto: true, map: true, person: "ryx" }],
  },
  caelus: {
    id: "caelus",
    act: "VII",
    place: "Caelus Hub",
    who: "Aeon Keeper Silas",
    bg: "/art/caelus-hub.jpg",
    portrait: "/art/silas.jpg",
    text: "Time as architecture. Silas already holds both names in a loop. Ryx Ronin’s name waits in an hour Azrael does not own yet. Four doors. The empty throne of Aeltharion does not sit you.",
    alt: "Silas does not greet you. He checks a ledger. Hour two is already written in a margin.",
    choices: [
      {
        id: "to-doors",
        tag: "Doors",
        label: "Walk the four doors.",
        auto: true,
        next: "doors",
        person: "silas",
      },
    ],
  },
  doors: {
    id: "doors",
    act: "VII",
    place: "The Hour",
    who: "Aeltharion",
    bg: "/art/aeltharion.jpg",
    portrait: "/art/aeltharion.jpg",
    text: "A god was murdered. Eden stopped trusting oaths and installed a System. You can mend the lattice, become a kinder cage, walk without a throne, or smash the lock. The meters have been listening.",
    alt: "The murdered sky remembers your last door. You may pick another. Ryx will crawl whichever one you leave.",
    choices: [
      { id: "door-mend", tag: "Mend", label: "Mend the lattice. Dual Flow as a door, not a weapon.", ending: "mend", oath: 8 },
      { id: "door-lock", tag: "Cage", label: "Become the lock. Safer. Smaller.", ending: "lock", ctrl: 8 },
      {
        id: "door-walk",
        tag: "Road",
        label: "Walk as Heartgrim walked. Immortal duty. No crown.",
        auto: true,
        ending: "walk",
      },
      { id: "door-shatter", tag: "Shatter", label: "Break the lock. Honest, not kind.", ending: "shatter" },
    ],
  },
};

export const CONTINENT_BEAT: Record<ContinentId, string> = {
  elysara: "wake",
  xihuang: "xihuang",
  nordheim: "nordheim",
  tezcal: "tezcal",
  abyssara: "abyssara",
  vindraeth: "vindraeth",
  caelus: "caelus",
};
